spring:
  application:
    name: AddressBook

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:addressbookdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    file:
      name: logs/application.log
    level:
      root: INFO
      com.example.AddressBook.Service.EmailService: DEBUG

  mail:
    host: smtp.gmail.com
    port: 587
    username: solankimayank028@gmail.com
    password: srxq hjmx pkti hnax
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  rabbitmq:
    addresses: localhost:5672

  data:
    redis:
      host: localhost
      port: 6379